### ISSUE TITLE
error when used on server

### ISSUE THREAD

**Issue by willhowlett** [emdgroup/aws4-tiny#1]
Trying this out as a solution to the massive client side bloat caused by aws4 - thanks for making it!

You say in the readme that it can be used on the server, however as it checks for window [here](https://github.com/emdgroup/aws4-tiny/blob/437d65774243d981d794a98dea9b4f9a1c56a4a5/src/index.js#L6) it seems to throw an error when I try it

**Comment by monken** [comment]
If you want to run this in a node process, you need to create an empty window object like this:
```
global.window = {};
```
This should allow you to run aws4-tiny. It's really not recommended though. `aws4` is actually quite small if you only run it in a node environment.
